<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="aae6daf3-7f0f-47fa-ba77-a51b203a8ff1" name="Fredrik@FKVAIO 2010-09-07 12:42:14" runUser="FKVaio\Fredrik" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="5b82bb5d-938d-47a6-8c5b-afaf40dc0149">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Fredrik_FKVAIO 2010-09-07 12_42_14" />
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2010-09-07T12:42:14.6523274+02:00" queuing="2010-09-07T12:42:14.9573448+02:00" start="2010-09-07T12:42:15.2713628+02:00" finish="2010-09-07T12:42:15.6393838+02:00" />
  <ResultSummary outcome="Failed">
    <Counters total="4" executed="4" error="0" failed="4" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="TaskPostponed_event_is_published" storage="c:\source\_projects\nexttask\nexttask.tests\bin\debug\nexttask.tests.dll" id="48190fb3-47e2-4c5f-b51b-b8f8d829603b">
      <Execution timeOut="1800000" id="35ad665d-5085-480e-919c-d536446503f2" />
      <TestMethod codeBase="C:/Source/_Projects/NextTask/NextTask.Tests/bin/Debug/NextTask.Tests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="NextTask.Tests.When_postponing_task, NextTask.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="TaskPostponed_event_is_published" />
    </UnitTest>
    <UnitTest name="Exception_is_thrown" storage="c:\source\_projects\nexttask\nexttask.tests\bin\debug\nexttask.tests.dll" id="98bb3bc4-05d4-f8e2-a91b-ad8e68c6fd76">
      <Execution timeOut="1800000" id="1a0f0e7d-8a0b-4df9-b292-c2d29d6653f1" />
      <TestMethod codeBase="C:/Source/_Projects/NextTask/NextTask.Tests/bin/Debug/NextTask.Tests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="NextTask.Tests.When_postponing_task_with_new_due_date_less_than_existing_due_date, NextTask.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Exception_is_thrown" />
    </UnitTest>
    <UnitTest name="TaskCancelled_event_is_published" storage="c:\source\_projects\nexttask\nexttask.tests\bin\debug\nexttask.tests.dll" id="7a533ce9-67f5-f9af-ad97-121a2f49f974">
      <Execution timeOut="1800000" id="6350ae13-53d4-424c-a66c-cb965477dda9" />
      <TestMethod codeBase="C:/Source/_Projects/NextTask/NextTask.Tests/bin/Debug/NextTask.Tests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="NextTask.Tests.When_completing_task, NextTask.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="TaskCancelled_event_is_published" />
    </UnitTest>
    <UnitTest name="TaskCancelled_event_is_published" storage="c:\source\_projects\nexttask\nexttask.tests\bin\debug\nexttask.tests.dll" id="28c8e7d6-deb0-1a4d-e172-64b990106212">
      <Execution timeOut="1800000" id="7aea1bd8-5b19-4c87-8ca3-fbdf14556c7b" />
      <TestMethod codeBase="C:/Source/_Projects/NextTask/NextTask.Tests/bin/Debug/NextTask.Tests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="NextTask.Tests.When_cancelling_task, NextTask.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="TaskCancelled_event_is_published" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="28c8e7d6-deb0-1a4d-e172-64b990106212" executionId="7aea1bd8-5b19-4c87-8ca3-fbdf14556c7b" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="7a533ce9-67f5-f9af-ad97-121a2f49f974" executionId="6350ae13-53d4-424c-a66c-cb965477dda9" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="48190fb3-47e2-4c5f-b51b-b8f8d829603b" executionId="35ad665d-5085-480e-919c-d536446503f2" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="98bb3bc4-05d4-f8e2-a91b-ad8e68c6fd76" executionId="1a0f0e7d-8a0b-4df9-b292-c2d29d6653f1" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="7aea1bd8-5b19-4c87-8ca3-fbdf14556c7b" testId="28c8e7d6-deb0-1a4d-e172-64b990106212" testName="TaskCancelled_event_is_published" computerName="FKVAIO" duration="00:00:00.1167285" startTime="2010-09-07T12:42:15.2913639+02:00" endTime="2010-09-07T12:42:15.5053762+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="7aea1bd8-5b19-4c87-8ca3-fbdf14556c7b">
      <Output>
        <ErrorInfo>
          <Message>Initialization method NextTask.Tests.When_cancelling_task.Setup threw exception. System.Reflection.TargetInvocationException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; Cqrs.UnknownDomainEventException: Aggregate root has no known handler for NextTask.Models.TaskCreated.</Message>
          <StackTrace>    at Cqrs.AggregateRoot.HandleEvent[TEvent](TEvent event) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 49
   at Cqrs.AggregateRoot.Apply[TEvent](TEvent event, Boolean isNew) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 38
   at Cqrs.AggregateRoot..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 22
   at NextTask.Domain.Task..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\NextTask.Domain\Task.cs:line 14
 --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle._InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct&amp; signature, RuntimeType declaringType)
   at System.RuntimeMethodHandle.InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct signature, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at NextTask.Tests.CommandTestFixture`3.BuildAggregate() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 51
   at NextTask.Tests.CommandTestFixture`3.Setup() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 28
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="6350ae13-53d4-424c-a66c-cb965477dda9" testId="7a533ce9-67f5-f9af-ad97-121a2f49f974" testName="TaskCancelled_event_is_published" computerName="FKVAIO" duration="00:00:00.0074349" startTime="2010-09-07T12:42:15.5153767+02:00" endTime="2010-09-07T12:42:15.5313777+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="6350ae13-53d4-424c-a66c-cb965477dda9">
      <Output>
        <ErrorInfo>
          <Message>Initialization method NextTask.Tests.When_completing_task.Setup threw exception. System.Reflection.TargetInvocationException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; Cqrs.UnknownDomainEventException: Aggregate root has no known handler for NextTask.Models.TaskCreated.</Message>
          <StackTrace>    at Cqrs.AggregateRoot.HandleEvent[TEvent](TEvent event) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 49
   at Cqrs.AggregateRoot.Apply[TEvent](TEvent event, Boolean isNew) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 38
   at Cqrs.AggregateRoot..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 22
   at NextTask.Domain.Task..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\NextTask.Domain\Task.cs:line 14
 --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle._InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct&amp; signature, RuntimeType declaringType)
   at System.RuntimeMethodHandle.InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct signature, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at NextTask.Tests.CommandTestFixture`3.BuildAggregate() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 51
   at NextTask.Tests.CommandTestFixture`3.Setup() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 28
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="35ad665d-5085-480e-919c-d536446503f2" testId="48190fb3-47e2-4c5f-b51b-b8f8d829603b" testName="TaskPostponed_event_is_published" computerName="FKVAIO" duration="00:00:00.0032241" startTime="2010-09-07T12:42:15.5363779+02:00" endTime="2010-09-07T12:42:15.5453785+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="35ad665d-5085-480e-919c-d536446503f2">
      <Output>
        <ErrorInfo>
          <Message>Initialization method NextTask.Tests.When_postponing_task.Setup threw exception. System.Reflection.TargetInvocationException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; Cqrs.UnknownDomainEventException: Aggregate root has no known handler for NextTask.Models.TaskCreated.</Message>
          <StackTrace>    at Cqrs.AggregateRoot.HandleEvent[TEvent](TEvent event) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 49
   at Cqrs.AggregateRoot.Apply[TEvent](TEvent event, Boolean isNew) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 38
   at Cqrs.AggregateRoot..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 22
   at NextTask.Domain.Task..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\NextTask.Domain\Task.cs:line 14
 --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle._InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct&amp; signature, RuntimeType declaringType)
   at System.RuntimeMethodHandle.InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct signature, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at NextTask.Tests.CommandTestFixture`3.BuildAggregate() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 51
   at NextTask.Tests.CommandTestFixture`3.Setup() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 28
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="1a0f0e7d-8a0b-4df9-b292-c2d29d6653f1" testId="98bb3bc4-05d4-f8e2-a91b-ad8e68c6fd76" testName="Exception_is_thrown" computerName="FKVAIO" duration="00:00:00.0028006" startTime="2010-09-07T12:42:15.5473786+02:00" endTime="2010-09-07T12:42:15.5513788+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="1a0f0e7d-8a0b-4df9-b292-c2d29d6653f1">
      <Output>
        <ErrorInfo>
          <Message>Initialization method NextTask.Tests.When_postponing_task_with_new_due_date_less_than_existing_due_date.Setup threw exception. System.Reflection.TargetInvocationException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; Cqrs.UnknownDomainEventException: Aggregate root has no known handler for NextTask.Models.TaskCreated.</Message>
          <StackTrace>    at Cqrs.AggregateRoot.HandleEvent[TEvent](TEvent event) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 49
   at Cqrs.AggregateRoot.Apply[TEvent](TEvent event, Boolean isNew) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 38
   at Cqrs.AggregateRoot..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 22
   at NextTask.Domain.Task..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\NextTask.Domain\Task.cs:line 14
 --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle._InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct&amp; signature, RuntimeType declaringType)
   at System.RuntimeMethodHandle.InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct signature, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at NextTask.Tests.CommandTestFixture`3.BuildAggregate() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 51
   at NextTask.Tests.CommandTestFixture`3.Setup() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 28
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>