<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="10f0ad8a-876a-4287-8602-7d56e9cfd92b" name="Fredrik@FKVAIO 2010-09-07 12:35:04" runUser="FKVaio\Fredrik" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="5b82bb5d-938d-47a6-8c5b-afaf40dc0149">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Fredrik_FKVAIO 2010-09-07 12_35_04" />
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2010-09-07T12:35:04.1967067+02:00" queuing="2010-09-07T12:35:04.5257255+02:00" start="2010-09-07T12:35:04.8357433+02:00" finish="2010-09-07T12:35:05.1737626+02:00" />
  <ResultSummary outcome="Failed">
    <Counters total="4" executed="4" error="0" failed="4" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="TaskPostponed_event_is_published" storage="c:\source\_projects\nexttask\nexttask.tests\bin\debug\nexttask.tests.dll" id="48190fb3-47e2-4c5f-b51b-b8f8d829603b">
      <Execution timeOut="1800000" id="e3efe8cf-6efc-4cc5-ad5a-e9833420d538" />
      <TestMethod codeBase="C:/Source/_Projects/NextTask/NextTask.Tests/bin/Debug/NextTask.Tests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="NextTask.Tests.When_postponing_task, NextTask.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="TaskPostponed_event_is_published" />
    </UnitTest>
    <UnitTest name="Exception_is_thrown" storage="c:\source\_projects\nexttask\nexttask.tests\bin\debug\nexttask.tests.dll" id="98bb3bc4-05d4-f8e2-a91b-ad8e68c6fd76">
      <Execution timeOut="1800000" id="b19d9bfe-5f45-4194-a24e-fbddb6aa9dab" />
      <TestMethod codeBase="C:/Source/_Projects/NextTask/NextTask.Tests/bin/Debug/NextTask.Tests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="NextTask.Tests.When_postponing_task_with_new_due_date_less_than_existing_due_date, NextTask.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Exception_is_thrown" />
    </UnitTest>
    <UnitTest name="TaskCancelled_event_is_published" storage="c:\source\_projects\nexttask\nexttask.tests\bin\debug\nexttask.tests.dll" id="7a533ce9-67f5-f9af-ad97-121a2f49f974">
      <Execution timeOut="1800000" id="0802442c-dbc9-45ea-99e8-e98944ff5fcf" />
      <TestMethod codeBase="C:/Source/_Projects/NextTask/NextTask.Tests/bin/Debug/NextTask.Tests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="NextTask.Tests.When_completing_task, NextTask.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="TaskCancelled_event_is_published" />
    </UnitTest>
    <UnitTest name="TaskCancelled_event_is_published" storage="c:\source\_projects\nexttask\nexttask.tests\bin\debug\nexttask.tests.dll" id="28c8e7d6-deb0-1a4d-e172-64b990106212">
      <Execution timeOut="1800000" id="c4821d15-05e0-434c-b89c-abd2fb2bb283" />
      <TestMethod codeBase="C:/Source/_Projects/NextTask/NextTask.Tests/bin/Debug/NextTask.Tests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="NextTask.Tests.When_cancelling_task, NextTask.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="TaskCancelled_event_is_published" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="28c8e7d6-deb0-1a4d-e172-64b990106212" executionId="c4821d15-05e0-434c-b89c-abd2fb2bb283" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="7a533ce9-67f5-f9af-ad97-121a2f49f974" executionId="0802442c-dbc9-45ea-99e8-e98944ff5fcf" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="48190fb3-47e2-4c5f-b51b-b8f8d829603b" executionId="e3efe8cf-6efc-4cc5-ad5a-e9833420d538" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="98bb3bc4-05d4-f8e2-a91b-ad8e68c6fd76" executionId="b19d9bfe-5f45-4194-a24e-fbddb6aa9dab" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="c4821d15-05e0-434c-b89c-abd2fb2bb283" testId="28c8e7d6-deb0-1a4d-e172-64b990106212" testName="TaskCancelled_event_is_published" computerName="FKVAIO" duration="00:00:00.1233957" startTime="2010-09-07T12:35:04.8337432+02:00" endTime="2010-09-07T12:35:05.0627563+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="c4821d15-05e0-434c-b89c-abd2fb2bb283">
      <Output>
        <ErrorInfo>
          <Message>Initialization method NextTask.Tests.When_cancelling_task.Setup threw exception. System.Reflection.TargetInvocationException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; Cqrs.UnknownDomainEventException: Aggregate root has no known handler for NextTask.Models.TaskCreated.</Message>
          <StackTrace>    at Cqrs.AggregateRoot.HandleEvent[TEvent](TEvent event) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 49
   at Cqrs.AggregateRoot.Apply[TEvent](TEvent event, Boolean isNew) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 38
   at Cqrs.AggregateRoot..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 22
   at NextTask.Domain.Task..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\NextTask.Domain\Task.cs:line 14
 --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle._InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct&amp; signature, RuntimeType declaringType)
   at System.RuntimeMethodHandle.InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct signature, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at NextTask.Tests.CommandTestFixture`3.BuildAggregate() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 51
   at NextTask.Tests.CommandTestFixture`3.Setup() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 28
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="0802442c-dbc9-45ea-99e8-e98944ff5fcf" testId="7a533ce9-67f5-f9af-ad97-121a2f49f974" testName="TaskCancelled_event_is_published" computerName="FKVAIO" duration="00:00:00.0033130" startTime="2010-09-07T12:35:05.0657564+02:00" endTime="2010-09-07T12:35:05.0707567+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="0802442c-dbc9-45ea-99e8-e98944ff5fcf">
      <Output>
        <ErrorInfo>
          <Message>Initialization method NextTask.Tests.When_completing_task.Setup threw exception. System.Reflection.TargetInvocationException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; Cqrs.UnknownDomainEventException: Aggregate root has no known handler for NextTask.Models.TaskCreated.</Message>
          <StackTrace>    at Cqrs.AggregateRoot.HandleEvent[TEvent](TEvent event) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 49
   at Cqrs.AggregateRoot.Apply[TEvent](TEvent event, Boolean isNew) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 38
   at Cqrs.AggregateRoot..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 22
   at NextTask.Domain.Task..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\NextTask.Domain\Task.cs:line 14
 --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle._InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct&amp; signature, RuntimeType declaringType)
   at System.RuntimeMethodHandle.InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct signature, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at NextTask.Tests.CommandTestFixture`3.BuildAggregate() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 51
   at NextTask.Tests.CommandTestFixture`3.Setup() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 28
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="e3efe8cf-6efc-4cc5-ad5a-e9833420d538" testId="48190fb3-47e2-4c5f-b51b-b8f8d829603b" testName="TaskPostponed_event_is_published" computerName="FKVAIO" duration="00:00:00.0027852" startTime="2010-09-07T12:35:05.0727568+02:00" endTime="2010-09-07T12:35:05.0827574+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="e3efe8cf-6efc-4cc5-ad5a-e9833420d538">
      <Output>
        <ErrorInfo>
          <Message>Initialization method NextTask.Tests.When_postponing_task.Setup threw exception. System.Reflection.TargetInvocationException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; Cqrs.UnknownDomainEventException: Aggregate root has no known handler for NextTask.Models.TaskCreated.</Message>
          <StackTrace>    at Cqrs.AggregateRoot.HandleEvent[TEvent](TEvent event) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 49
   at Cqrs.AggregateRoot.Apply[TEvent](TEvent event, Boolean isNew) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 38
   at Cqrs.AggregateRoot..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 22
   at NextTask.Domain.Task..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\NextTask.Domain\Task.cs:line 14
 --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle._InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct&amp; signature, RuntimeType declaringType)
   at System.RuntimeMethodHandle.InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct signature, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at NextTask.Tests.CommandTestFixture`3.BuildAggregate() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 51
   at NextTask.Tests.CommandTestFixture`3.Setup() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 28
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="b19d9bfe-5f45-4194-a24e-fbddb6aa9dab" testId="98bb3bc4-05d4-f8e2-a91b-ad8e68c6fd76" testName="Exception_is_thrown" computerName="FKVAIO" duration="00:00:00.0034345" startTime="2010-09-07T12:35:05.0847575+02:00" endTime="2010-09-07T12:35:05.0947581+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="b19d9bfe-5f45-4194-a24e-fbddb6aa9dab">
      <Output>
        <ErrorInfo>
          <Message>Initialization method NextTask.Tests.When_postponing_task_with_new_due_date_less_than_existing_due_date.Setup threw exception. System.Reflection.TargetInvocationException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; Cqrs.UnknownDomainEventException: Aggregate root has no known handler for NextTask.Models.TaskCreated.</Message>
          <StackTrace>    at Cqrs.AggregateRoot.HandleEvent[TEvent](TEvent event) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 49
   at Cqrs.AggregateRoot.Apply[TEvent](TEvent event, Boolean isNew) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 38
   at Cqrs.AggregateRoot..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 22
   at NextTask.Domain.Task..ctor(IEnumerable`1 events) in C:\Source\_Projects\NextTask\NextTask.Domain\Task.cs:line 14
 --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle._InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct&amp; signature, RuntimeType declaringType)
   at System.RuntimeMethodHandle.InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct signature, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at NextTask.Tests.CommandTestFixture`3.BuildAggregate() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 51
   at NextTask.Tests.CommandTestFixture`3.Setup() in C:\Source\_Projects\NextTask\NextTask.Tests\CommandTestFixture.cs:line 28
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>